### ISSUE TITLE
Windowsで動作しない

### ISSUE THREAD

**Issue by y-chan** [y-chan/node-voicevox-engine#1]
なんでだよ！って内心めっちゃ思ってますが、動かないものは動かないので何とかしたいです。

現状、動的にリンクしているコア周りの関数をたたくと落ちることが分かっています。
ただ、これ以上糸口が見つからないといった状況です。

**Comment by buckw6eat** [comment]
かなり雑なコメントで恐縮ですが、大体の `vector<long>` を `vector<int64_t>` に置き換えてみてください。
https://cpprefjp.github.io/reference/cstdint/int64_t.html

long* の時点ではまぁいいんですが (ポインターは 64bit バイナリーは 64bit と考えてよい)、long のメモリーは Windows では 32bit 幅要素、Linux では 64bit 幅要素なのです。
